name: fast_trivia
description: Teste técnico do recrutamento CheckMob.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_database: ^10.2.5
  cloud_firestore: ^4.8.5
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash: 
  color: "#262329"
  image: lib/core/assets/images/logo.png
  
flutter:
  uses-material-design: true
  
  assets:
    - lib/core/assets/images/logo.png
    - lib/core/assets/json/quiz.json